-- Beginning of "transportation_costs_schema.sql"
CREATE TABLE transportation_costs(
    customer-1 INT
    , customer-2 INT
    , customer-3 INT
    , customer-4 INT
    , customer-5 INT
    , customer-6 INT
    , customer-7 INT
    , customer-8 INT
    , customer-9 INT
    , customer-10 INT
    , customer-11 INT
    , customer-12 INT
    , customer-13 INT
    , customer-14 INT
    , customer-15 INT
    , customer-16 INT
    , customer-16 INT
    , customer-17 INT
    , customer-18 INT
    , customer-19 INT
    , customer-20 INT
    , customer-21 INT
    , customer-22 INT
    , customer-23 INT
    , customer-24 INT
    , customer-25 INT
    , customer-26 INT
    , customer-27 INT
    , customer-28 INT
    , customer-29 INT
    , customer-30 INT
    , customer-31 INT
    , customer-32 INT
    , customer-33 INT
    , customer-34 INT
    , customer-35 INT
    , customer-36 INT
    , customer-37 INT
    , customer-38 INT
    , customer-39 INT
    , customer-40 INT
    , customer-41 INT
    , customer-42 INT
    , customer-43 INT
    , customer-44 INT
    , customer-45 INT
    , customer-46 INT
    , customer-47 INT
    , customer-48 INT
    , customer-49 INT
    , customer-50 INT
    , customer-51 INT
    , customer-52 INT
    , customer-53 INT
    , customer-54 INT
    , customer-55 INT
    , customer-56 INT
    , customer-57 INT
    , customer-58 INT
    , customer-59 INT
    , customer-60 INT
    , customer-61 INT
    , customer-62 INT
    , customer-63 INT
    , customer-64 INT
    , customer-65 INT
    , customer-66 INT
    , customer-67 INT
    , customer-68 INT
    , customer-69 INT
    , customer-70 INT
    , customer-71 INT
    , customer-72 INT
    , customer-73 INT
    , customer-74 INT
    , customer-75 INT
    , customer-76 INT
    , customer-77 INT
    , customer-78 INT
    , customer-79 INT
    , customer-80 INT
    , customer-81 INT
    , customer-82 INT
    , customer-83 INT
    , customer-84 INT
    , customer-85 INT
    , customer-86 INT
    , customer-87 INT
    , customer-88 INT
    , customer-89 INT
    , customer-90 INT
    , customer-91 INT
    , customer-92 INT
    , customer-93 INT
    , customer-94 INT
    , customer-95 INT
    , customer-96 INT
    , customer-97 INT
    , customer-98 INT
    , customer-99 INT
    , customer-100 INT
    , customer-101 INT
    , customer-102 INT
    , customer-103 INT
    , customer-104 INT
    , customer-105 INT
    , customer-106 INT
    , customer-107 INT
    , customer-108 INT
    , customer-109 INT
    , customer-110 INT
    , customer-111 INT
    , customer-112 INT
    , customer-113 INT
    , customer-114 INT
    , customer-115 INT
    , customer-116 INT
    , customer-117 INT
    , customer-118 INT
    , customer-119 INT
    , customer-120 INT
    , customer-121 INT
    , customer-122 INT
    , customer-123 INT
    , customer-124 INT
    , customer-125 INT
);
-- End of "transportation_costs_schema.sql"
