-- Beginning of "transportation_costs_schema.sql"
CREATE TABLE transportation_costs(
    customer_1 INT
    , customer_2 INT
    , customer_3 INT
    , customer_4 INT
    , customer_5 INT
    , customer_6 INT
    , customer_7 INT
    , customer_8 INT
    , customer_9 INT
    , customer_10 INT
    , customer_11 INT
    , customer_12 INT
    , customer_13 INT
    , customer_14 INT
    , customer_15 INT
    , customer_16 INT
    , customer_17 INT
    , customer_18 INT
    , customer_19 INT
    , customer_20 INT
    , customer_21 INT
    , customer_22 INT
    , customer_23 INT
    , customer_24 INT
    , customer_25 INT
    , customer_26 INT
    , customer_27 INT
    , customer_28 INT
    , customer_29 INT
    , customer_30 INT
    , customer_31 INT
    , customer_32 INT
    , customer_33 INT
    , customer_34 INT
    , customer_35 INT
    , customer_36 INT
    , customer_37 INT
    , customer_38 INT
    , customer_39 INT
    , customer_40 INT
    , customer_41 INT
    , customer_42 INT
    , customer_43 INT
    , customer_44 INT
    , customer_45 INT
    , customer_46 INT
    , customer_47 INT
    , customer_48 INT
    , customer_49 INT
    , customer_50 INT
    , customer_51 INT
    , customer_52 INT
    , customer_53 INT
    , customer_54 INT
    , customer_55 INT
    , customer_56 INT
    , customer_57 INT
    , customer_58 INT
    , customer_59 INT
    , customer_60 INT
    , customer_61 INT
    , customer_62 INT
    , customer_63 INT
    , customer_64 INT
    , customer_65 INT
    , customer_66 INT
    , customer_67 INT
    , customer_68 INT
    , customer_69 INT
    , customer_70 INT
    , customer_71 INT
    , customer_72 INT
    , customer_73 INT
    , customer_74 INT
    , customer_75 INT
    , customer_76 INT
    , customer_77 INT
    , customer_78 INT
    , customer_79 INT
    , customer_80 INT
    , customer_81 INT
    , customer_82 INT
    , customer_83 INT
    , customer_84 INT
    , customer_85 INT
    , customer_86 INT
    , customer_87 INT
    , customer_88 INT
    , customer_89 INT
    , customer_90 INT
    , customer_91 INT
    , customer_92 INT
    , customer_93 INT
    , customer_94 INT
    , customer_95 INT
    , customer_96 INT
    , customer_97 INT
    , customer_98 INT
    , customer_99 INT
    , customer_100 INT
    , customer_101 INT
    , customer_102 INT
    , customer_103 INT
    , customer_104 INT
    , customer_105 INT
    , customer_106 INT
    , customer_107 INT
    , customer_108 INT
    , customer_109 INT
    , customer_110 INT
    , customer_111 INT
    , customer_112 INT
    , customer_113 INT
    , customer_114 INT
    , customer_115 INT
    , customer_116 INT
    , customer_117 INT
    , customer_118 INT
    , customer_119 INT
    , customer_120 INT
    , customer_121 INT
    , customer_122 INT
    , customer_123 INT
    , customer_124 INT
    , customer_125 INT
);
-- End of "transportation_costs_schema.sql"
